var tipuesearch = {
  "pages": [{
    "text": "Since Hardin, law and economics scholars have launched a crusade to expose the evil of the commons - the evil, that is, of not propertizing. Progressive legal scholars have responded in kind, exposing the perils of propertization. With the rise of the Information Age, the flashpoint debates about property have moved from land to information. The public domain is now the cause c\u00e9l\u00e8bre among progressive intellectual property and cyber-law scholars, who extol the public domain as necessary for sustaining innovation. But scholars obscure the distributional consequences of the commons. They presume a landscape where every person can reap the riches found in the commons. This is the romance of the commons - the belief that because a resource is open to all by force of law, it will indeed be equally exploited by all. But in practice, differing circumstances - including knowledge, wealth, power, access, and ability - render some better able than others to exploit a commons.\nWe examine this romance through the lens of the global intellectual property regime in genetic resources and traditional knowledge. The Agreement on Trade Related Aspects of Intellectual Property Rights (TRIPS) transformed a global public domain in information by propertizing the information resources of the West - from entertainment to technological advances - but leaving in the commons the information resources of the rest of the world, such as genetic resources and traditional knowledge. Just as the trope of the romantic author has served to bolster the property rights claims of the powerful, so too does the romance of the public domain. Resourcefully, the romantic public domain trope steps in exactly where the romantic author falters. Where genius cannot justify the property claims of corporations (because the knowledge pre-exists individual claims of authorship), the public domain can. We review real-world strategies for resolving the romance of the commons. Just as recognition of the tragedy of the commons is the central justification for private property, recognizing the romance of the commons may justify forms of property uncommon in Western legal traditions.",
    "title": "The Romance of the Public Domain",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Is the libertarian vision of Nozick in ascendance in intellectual property, overshadowing Rawls's egalitarianism?  Yes, and rightly so, some intellectual property scholars suggest.  They argue that intellectual property law seeks to solve a fundamental problem of information economics:  without intellectual property protections, the ready duplicability of information undermines incentives to create information.  Armed with this economic insight and fortified a neo-liberal faith that markets with well-defined property rights in information will best promote liberty, these scholars would keep intellectual property's focus single-minded: to incentivize the production of information.\nIn this introduction to a symposium on \"Intellectual Property and Social Justice,\" we argue that this view is too narrow.  A variety of societal goals must inform intellectual property law because (1) understanding intellectual property's impact on a variety of social values helps us restrain maximalist intellectual property demands; (2) relying on the tax and welfare systems to remedy any resulting distributional deficiencies is unrealistic; (3) the raison d'etre of Western intellectual property laws is not necessarily globally scalable because of varying capacities to innovate; (4) we must attend to the kind of innovation that law spurs (for example, does the existing regime adequately incentivize the discovery of treatments for poor people's diseases?); and (5) we can best understand fair use doctrine not just as market failure but as an important component of free speech.\nThe fact that a legal regime might be created for one purpose should not mean that the implications of that regime for all other purposes should be ignored.  The state raises an army because of the need to assure its security against foreign invasions.  Yet, the state might deploy the army domestically in case of natural disasters.  And it might establish limits on how the army might operate (such as prohibitions on torture and sexual harassment) - limits stemming not necessarily from self-defense but from other human values.  Similarly, the fact that intellectual property law might be established for instrumental reasons does not mean that other purposes should not be considered when we set its metes and bounds.",
    "title": "Is Nozick Kicking Rawls's Ass? Intellectual Property and Social Justice",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "In the wake of the global financial crisis, American and European regulators quickly converged on a reform intended to help stave off similar crises in the future: central counterparty clearinghouses for credit default swaps. On both sides of the Atlantic, regulators identified credit default swaps (CDS) as a central factor in the crisis that seized Bear Stearns, Lehman Brothers, American International Group (AIG), and ultimately global credit markets. Introducing a well-capitalized central counterparty between CDS buyers and sellers would, regulators came to believe, help contain financial failures in the future.\nHow and why did this convergence occur? This Article reviews the American and European responses, concluding that they converged on a similar structure largely because the financial crisis revealed the vulnerabilities of a system in which buyers and sellers entered into CDS directly, through bilateral contracts. These bilateral derivatives contracts created a web of interconnected obligations, such that the failure of one firm could bring down a chain of others. The threat of this domino effect led governments to intervene in the financial markets with massive direct and indirect support. Forced to spend public money to bail out private firms, regulators risked an unsustainable moral hazard - firms that were \u201cToo Interconnected to Fail.\u201d Regulators concluded that the introduction of a central counterparty (CCP) would reduce the risk that the bankruptcy of a principal in a credit default swap would precipitate a domino fall through the credit markets. Where critics argue that CCPs concentrate risk, regulators came to recognize that Bear, Lehman, and AIG had each also concentrated risk, serving as de facto central clearing counterparties, lacking the disciplines of a regulated CCP.",
    "title": "Clearing Credit Default Swaps: A Case Study in Global Legal Convergence",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Lieutenant Mary Sue took the helm of the Starship Enterprise, saving the ship while parrying Kirk's advances. At least she did so in the unofficial short story by Trekkie Paula Smith. Mary Sue has since come to stand for the insertion of an idealized authorial representative in a popular work. Derided as an exercise in narcissism, Mary Sue is in fact a figure of subaltern critique, challenging the stereotypes of the original. The stereotypes of popular culture insinuate themselves deeply into our lives, coloring our views on occupations and roles. From Hermione Granger-led stories, to Harry Potter in Kolkata, to Star Trek same-sex romances, Mary Sues re-imagine our cultural landscape, granting agency to those denied it in the popular mythology. Lacking the global distribution channels of traditional media, Mary Sue authors now find an alternative in the World Wide Web, which brings their work to the world.\nDespite copyright law's grant of rights in derivative works to the original's owners, we argue that Mary Sues that challenge the orthodoxy of the original likely constitute fair use. The Mary Sue serves as a metonym for all derivative uses that challenge the hegemony of the original. Scholars raise three principal critiques to such unlicensed use: (1) why not write your own story rather than borrowing another's? (2) even if you must borrow, why not license it? and (3) won't recoding popular icons destabilize culture? Relying on a cultural theory that prizes voice, not just exit, as a response to hegemony, we reply to these objections here.",
    "title": "Everyone's a Superhero: A Cultural Theory of 'Mary Sue' Fan Fiction as Fair Use",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Diasporas play a central role in the international system, disseminating information, transmitting capital and transforming culture. Defying national borders, they challenge the basic conception of the nation-state system, yet international law has not begun to notice them. They challenge traditional views of citizenship, as well, yet they have escaped the attention of domestic public law scholars.\nThis paper begins to conceptualize diasporas as a topic of legal inquiry. Diasporas undermine both the traditional statist conception of a citizenry with a singular national loyalty and the cosmopolitan alternative that denies the moral salience of states in favor of a world citizenship. The paper proposes a third paradigm of the relationship of citizen to state, a diaspora model that embraces diasporas as emblematic of a globalized world where history matters yet does not constrict.\nThe paper applies its analytical framework to international bonds issued by governments to their diasporas. These \"Diaspora Bonds\" allow homeland governments to turn to their diasporas to raise capital for economic development.",
    "title": "Diaspora Bonds",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Who rules Facebookistan? Who makes the rules that govern the way a tenth of humanity connects on the Internet? The United States, France, China, or Mark Zuckerberg? Facebook represents a type of multinational corporation new to the world stage \u2014 one that raises issues different than those raised by earlier generations of multinational corporations. A review of international controversies involving Facebook reveals that Facebook has changed some of its policies as a result of pressures from governments around the world, while resisting other pressures. At the same time, Facebook has itself helped spur changes in the law, most evidently in helping undermine repressive governments. Ultimately, this Article finds that regulatory power is, de facto, dispersed across a wide array of international actors.",
    "title": "Facebookistan",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Already, the world of cyberspace is beginning to replicate the inequalities of real space.  The distribution of domain names, a basic building block of e-commerce, shows dramatic disparities between the high and low income parts of the world.  Americans own most of the world's domain names, including the names of faraway countries, tribes, and cultural events, such as SouthAfrica.com, Yanomami.com, and KumbhMela.com.  No African or South American company has the lucrative charter that would allow it to award global domain names.  The principal cause of this inequality is a domain name system that follows a rule of first possession.  This Article critiques this property rule as being founded less on moral reasoning than on an assertion of power.  Going further still, the Article argues that the current property rights regime in domain names cannot be justified by any of the traditional philosophical or economic theories underlying our private property system.\nIn rethinking entitlements to domain names, the Article turns to the history of the American public lands and the international law regimes governing global commons spaces, such as the ocean bed, outer space, and Antarctica.  We see in each of these cases the effort to craft a system that allocates rights to a common or global resource paying heed to social goals such as distributive justice, environmental protection, and economic development.  Thus far, scholars and policy-makers have not paused to consider any such concerns for the world of cyberspace.  Drawing upon the insights of diverse disciplines, this Article proposes a global domain name regime that comports with concerns for equality and distributive justice.",
    "title": "The New, New Property",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Cyber-law is today\u2019s speech law. When civic engagement is increasingly mediated online, the law regulating cyberspace becomes the law regulating speech. Yet, free speech texts pay little attention to the ways that cyber-law configures what has become the principal mechanism for exercising free speech rights today \u2014 communication online. Conversely, while many have long observed that the Internet enables speech, scholars have failed to recognize the role that the First Amendment played in shaping the law of cyberspace. A First Amendment-infused legal culture that prizes speech proved an ideal environment on which to build the speech platforms that make up Web 2.0. Free speech was Silicon Valley\u2019s killer app.\nToday\u2019s speech law is being made in the major cyber-law disputes of the day. From the Stop Online Piracy Act, criminal copyright enforcement, and a plurilateral free trade treaty, to United Nations control of the Internet, the European Union\u2019s proposed right to be forgotten, and the revelations of pervasive NSA surveillance, cyber-law controversies show that we are still seeking to translate free speech values into the Information Age. How we approach these disputes will determine the extent of government censorship, private third-party censorship and self-censorship. This article offers a framework for resolving cyber-law disputes, duly attendant to their speech implications.",
    "title": "Free Speech",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "While GM and GE are rushing in to China, why are so many Americans cheering the possibility of Google pulling out? The answer to this puzzle lies in Google\u2019s special role as new media. Television once moved the free speech paradigm from the local street corner to the national platform of CBS; the Internet has shifted it further to the global stage offered by Google and its peers. Free speech theory \u2013 and Western media corporations \u2013 must now grapple with the reach of this media into unfree societies. While a growing chorus has denounced Western new media enterprises for betraying their obligations to the people of China and other authoritarian regimes, no one has yet explained what those obligations are or why these companies might have them. Corporate social responsibility theory has focused largely on the risks of a global supply chain in goods, neglecting the questions raised by the rise of global information services. The notion of corporate obligations to people around the world seems especially perplexing in juxtaposition with the familiar mandate to maximize shareholder wealth at home. Drawing from theories of Foucault and Habermas and the history of the underground press, I argue that information service providers bear a special responsibility to unfree people. What might have been mutually beneficial transactions in a free society can become, in an unfree society, predicate offenses leading to years of hard labor. New media can either help give voice to dissidents or help perfect totalitarianism.\u0000",
    "title": "Googling Freedom",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "null",
    "title": "Globalization and Distrust",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Can trade liberalization serve the cause of political liberalization in authoritarian states? In this short essay, I suggest that trade law might bolster political freedoms by liberalizing Internet trade. Trade law puts pressure on state repression of information through two principal mechanisms.\nFirst, GATS transparency obligations require what is often absent in authoritarian states \u2013 a set of public rules that governs both citizens and governmental authorities. WTO member states must publish regulations governing services and establish inquiry points where foreign service providers can obtain information about such regulations. A publication requirement written for the benefit of foreigners may prove even more useful for local citizens, who will be given the opportunity to understand the rules that bind them \u2013 and the opportunity therefore to challenge those rules or their interpretation.\nSecond, the market access and national treatment commitments provide opportunities for foreign information service providers to disseminate information that local information service providers might eschew. While censorship by itself may not necessarily constitute either a market access or a national treatment violation, it might do so if it is operationalized in ways that effectively discriminate against foreign service providers.",
    "title": "International Trade and Internet Freedom",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Will the Internet help topple tyrants, or will it help further cement their control? Prominent skeptics challenge the notion that the Internet will help rid the world of dictators. They suggest that the Internet will simply serve as a new opiate of the masses, or worse, will assist autocrats in manipulating popular opinion. I defend the liberalizing promise of cyberspace. Where others have set out the value of the Internet to dissidents, I answer the main critiques of that position - that Internet activism is futile, that the Internet is simply the new opiate of the masses, and that autocrats will benefit more from the Internet than dissidents. I argue that dictators have revealed their own appraisals of the Internet: when threatened, they shut it down. Tyrants today fear the Internet more than they benefit from it. This summer\u2019s events again confirmed this truth: On the day when the rebels marched into Tripoli, they restored Libya to the Internet.",
    "title": "Jasmine Revolutions",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Where the last century saw the dismantling of barriers to trade in goods, the new century will see the dismantling of barriers to trade in services. Once theorized as nontradable, services now join goods in a global marketplace powered by advances in communications technology. Today, an engineer, accountant, or lawyer can supply her services across the globe without boarding a plane. Less well understood is that cyber-trade encompasses not just the services outsourced to Bangalore, but also the online services supplied by Silicon Valley to the world. Apple, eBay, and Yahoo too are exporters of information services, seeking to become middlemen to the world. Google now earns half of its income overseas. Almost sub rosa, the Internet has become a global trading platform rivaling any history has yet produced. But law developed over millennia for the paradigm of goods is unprepared for trade, version 2.0.\nThe pressure on law is clear: Antigua challenges U.S. rules barring online gambling; Brazil demands that Google identify hate speakers; an Alien Torts Statute suit charges Yahoo with abetting Chinese torture; and the United States challenges Chinese media restrictions on movie, music, and financial information services. Once we recognize the connections between these disputes, we can begin to form a general theory of cyber-trade. Ricardo\u2019s theory of comparative advantage applies to all trade, whether in goods or in information. Economic theory thus counsels, and international treaties compel, the dismantling of barriers to cyber-trade. Yet, because of its remote nature, it is easy to assert consumer protection to bar online competition. I articulate a principle of technological neutrality to smoke out barriers hiding under this veneer. To flourish, cyber-trade will also require digital analogues to the physical infrastructure for services, from handshakes to courts.\nThe footloose nature of cyber-trade poses a more fundamental challenge - to law itself. Via the net, service providers can flout local law from afar. This race to the bottom arises from the exploitation of overly liberal regimes, lacking consumer and other protections. A second potential race to the bottom arises from overly repressive regimes, which require service providers to serve as auxiliaries of the authoritarian state. I offer principles to protect local control of global Internet trade without jeopardizing either human rights or the World-Wide nature of the Web.",
    "title": "Trade 2.0",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Explanations for the success of Silicon Valley focus on the confluence of capital and education. In this article, I put forward a new explanation, one that better elucidates the rise of Silicon Valley as a global trader. Just as nineteenth century American judges altered the common law in order to subsidize industrial development, American judges and legislators altered the law at the turn of the Millennium to promote the development of Internet enterprise. Europe and Asia, by contrast, imposed strict intermediary liability regimes, inflexible intellectual property rules, and strong privacy constraints, impeding local Internet entrepreneurs. The study challenges the conventional wisdom that holds that strong intellectual property rights undergird innovation. While American law favored both commerce and speech enabled by this new medium, European and Asian jurisdictions attended more to the risks to intellectual property rights-holders and, to a lesser extent, ordinary individuals. Innovations that might be celebrated in the United States could lead to jail in Japan. I show how American companies leveraged their liberal home base to become global leaders in cyberspace. Nations seeking to incubate their own Silicon Valley must focus not only on money and education, but also a law that embraces innovation.",
    "title": "How Law Made Silicon Valley",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "A BRICS Internet, the Euro Cloud, the Iranian \u201cHalal\u201d Internet: Governments across the world eager to increase control over the World Wide Web are tearing it apart. Iran seeks to develop an Internet free of Western influences or domestic dissent. The Australian government places restrictions on health data leaving the country. Russia requires personal information to be stored domestically. Vietnam insists on a local copy of all Vietnamese data. The last century\u2019s nontariff barriers to goods have reappeared as firewalls blocking international services. Legitimate global anxieties over surveillance and security are justifying governmental measures that break apart the World Wide Web, without enhancing either privacy or security.\nThe issue is critical to the future of international trade and development, and even to the ongoing struggle between democracy and totalitarianism. Data localization threatens the possibility of outsourcing services, whether to Bangalore, Accra, Manila, or even Silicon Valley. The theory of this Article expands the conversation about international Internet regulation from efforts to prevent data from flowing in to a country through censorship, to include efforts to prevent data from flowing out through data localization. A simple formula helps demonstrate what is stake: censorship   data localization = total control.",
    "title": "Data Nationalism",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Legalized Racism: The Internment of Japanese Americans",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "The odious debt doctrine exposes a fundamental dilemma in international finance - the desire not to saddle a population with a debt to which it did not consent and from which it did not benefit, coupled with a practical need to ensure that capital continues to flow.  The odious debt doctrine would undermine international debt obligations of a state that are entered into (1) without the consent of the people; (2) not for the benefit of the people; and (3) both of the above with the knowledge of the creditors.  This Essay raises questions about the doctrine with respect to each of these criteria: (1) Given the dazzling variety of modern financial products, how should we define the types of debt obligations subject to the doctrine?  (2) Should the fact that the proceeds of a loan are used in part for the commonweal defeat the application of the doctrine?  (3) Should the broad, deep, and faceless capital markets offer an escape from culpability for the financiers of international delicts because public bondholders are to be presumed unfamiliar with the credit?  The Essay offers observations on each of these issues.",
    "title": "Odious Securitization",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Where once the emigrant was remembered in her homeland through yellowing photographs, eventually perhaps forgotten to history or even cursed as a traitor, the emigrant today is celebrated, reconfigured as heroine.  As Kim Barry argues in Home and Away, homeland states now see the emigrant as crucial to their projects of national advancement.\nToday, states undertake a variety of bonding mechanisms - political, economic, and cultural - seeking to strengthen their ties to their diasporas.  I survey such bonding mechanisms, offering a taxonomy that connects governmental policies from Mexico to the Philippines.  Governments seeking to cement political ties have offered dual citizenship, voting from abroad, direct representation of expatriates, special visas for the diaspora, and government-issued diaspora membership documents.  States have sought to capitalize on the economic strength of their overseas members by soliciting their support for sovereign diaspora bonds, development programs, and direct investment.  They have also sought to attract returnees, who will often bring with them significant financial and human capital, and to ease return by negotiating for returnees' pensions to be transferred to them from the nation in which they worked.  Finally, nations have sought to reshape their own collective image to include the diaspora, achieving this through explicit state recognition of the diaspora, establishment of agencies to serve the diaspora, legal protections for their overseas citizens, and special outreach to youth and retirees living abroad.\nI ask to what extent such bonding practices are subject to regulation by the emigrant's host country.  I assess constraints on such regulation in the United States created by the freedoms of association, speech, and travel.  U.S. laws of general applicability, such as securities laws, and U.S. courts' unwillingness to enforce foreign revenue laws may make it more difficult for emigration states to pursue certain bonding mechanisms.  Despite these limits, the domestic laws of immigration states like the United States should provide sufficient space for emigration states to bond with their diasporas.",
    "title": "Homeward Bound",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Robots, the Internet of Things, and the Future of Trade",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Corporate law understands what constitutional law does not. Minority status matters to law. Where today's constitutional jurisprudence of equal protection aspires to colorblindness, corporate law places minority concerns at the heart of its endeavor. The minorities of corporate law are minority shareholders - investors holding small, noncontrolling interests in the corporation. By contrasting corporate and constitutional law, I begin to conceptualize \"minority\" status as a legal fact.\nI begin by rereading the corporate canon. I show that body's concern not just for wealth maximization, but also its distribution. I reveal corporate law's deep commitment to protecting minority shareholders, operationalized through an elaborate common law and statutory framework.\nI then apply corporate law's theory of minorities to three hot button debates in the constitutional law realm: affirmative action (recently addressed by the Supreme Court in Grutter and Gratz), California's Racial Privacy Initiative (put to vote in 2003), and the demographic shift to a majority minority polity (already reality in California).",
    "title": "Minorities, Shareholder and Otherwise",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "The printing press helped create modern nationalisms, as books and newspapers came to be written in the vernacular, encouraging a conception of a shared community among groups of people who would never actually meet.  It thus seems only natural to ask what today's innovation in mass communication, the Internet, will mean for political communities.  In his book, REPUBLIC.COM (2001), Cass Sunstein contends that the advent of personalized information sources available in cyberspace threatens republican deliberation.  But where Sunstein worries about the \"Daily Me\" made possible by electronic intermediaries that deliver news tailored to a reader's tastes, I observe that, for minorities, the traditional media offer the \"Daily Them\" - a vision of society focused on its dominant members.\nI suggest that cyberspace helps counter the elision of minority experiences in the traditional media.  Because of technical features such as end-to-end design, the Internet and the World-Wide-Web enhance the ability of marginalized people to have their voices heard, and indeed to find a voice.  At the same time, cyberspace may help reinvent community, pulling us out of territorially-imagined spaces in favor of transnational, affective communities.  In many ways, cyberspace presents a cosmopolitan ideal, where individuals may be drawn together based on interests and passions, rather than territory or national identity.",
    "title": "Whose Republic?",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Unshackling Foreign Corporations:  Kiobel\u2019s Unexpected Legacy",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Exporting DMCA Lockouts",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "This paper addresses the question of whether it is possible to balance the need for a free flow of information across borders with legitimate government concerns related to public order, consumer privacy, and security. The paper begins by highlighting the risks associated with limitations on free information flows and the policy concerns that lead to these limitations. The paper then provides an analysis of the current international regime on cross-border information flows. The authors argue that specific binding trade language promoting cross-border flows \u2014 combined with continued international cooperation \u2014 will enhance, rather than undermine, public order, national security, and privacy.",
    "title": "Information Goes Global: Protecting Privacy, Security, and the New Economy in a World of Cross-Border Data Flows",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "How might an Asian Century to come differ from the American Century just past? Will an Asian Century, should it come to pass, mark a retreat for human rights, including women\u2019s rights and gay rights? In this introduction to a UC Davis Law Review symposium, I contrast Henry Luce\u2019s vision for an American Century with the internationalism of his near contemporary, the Indian Poet Laureate Rabindranath Tagore. As the United States entered World War II, Luce, publisher of Time, Life, and Fortune, asked, \u201cWhat are we fighting for?\u201d Luce\u2019s manifesto declaring an \u201cAmerican Century\u201d answered that it was the internationalization of American ideas - promulgated from Hollywood to Washington. Luce\u2019s vision presaged American support for human rights after the war and its forceful, if inconsistent, critique of despots during the latter half of the Twentieth Century.\nIn the Post-War era, China and India embraced the sovereign nation-state, often proving reluctant to support intervention in the affairs of other countries, even when human rights were at stake. Tagore offered an alternative vision. Hailing from a land that long suffered at the hands of British traders and imperialists, Tagore proposed an internationalism led by neither the merchant nor the soldier. Instead, Tagore offered a world order founded on a kind of critical friendship, unflinchingly focused on human dignity for all.",
    "title": "The Asian Century?",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Copyright's Cultural Turn",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "The Internet was supposed to end geography. Anyone, anywhere could now run a newspaper, a search engine, a game service, and the world could access it. After millennia of geography dictating destiny, the world was now flat, and opportunity evenly distributed everywhere. Yet, a quick glance at the world\u2019s leading internet companies, from Facebook to Zillow, leads one remarkably often to the United States. In this article, I argue that law played a crucial role in creating the geography of cyberspace \u2014 specifically, that flexible intellectual property rules which permitted internet entrepreneurship in the United States proved a key ingredient in American commercial success on the Internet.",
    "title": "Law and the Geography of Cyberspace",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "I respond to Steve Bainbridge's critique of my 2005 Yale Law Journal essay, Minorities, Shareholder and Otherwise. My essay made two novel claims: that corporate law places protection of minority shareholders at the heart of its endeavor; and that this minority-mindfulness should have even greater purchase in constitutional contexts. In his new paper, Bainbridge challenges my account of corporate law's solicitude for minority shareholders, suggesting that corporate law does not practice affirmative action for minority shareholders.\nI rebut Bainbridge's case analysis, demonstrating that the cases show clear judicial succor for minority (by which I mean non-controlling) shareholders. The overarching explanation for judicial action in corporate law matters can generally be found in the simple goal of protecting minority shareholders. Unlike current constitutional jurisprudence, then, corporate law does not embrace minority-blindness. Because of, or despite, a legal framework attentive to the most vulnerable among those contributing capital, corporations have proven to be remarkably successful forms of enterprise. Ultimately, I hope to spur the thought that human organizational forms stand to learn much from each other.",
    "title": "Corporate Law's Distributive Design",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Fred Korematsu: All American Hero",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Book Review of Transnational Litigation in United States Courts",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Should minority status be a relevant datum for judicial decision? That is the question motivating my paper, Minorities, Shareholder and Otherwise, published a handful of years ago in the Yale Law Journal. This short essay published in the Yale Law Journal Online introduces an online symposium revisiting that work, with responses from Stephen Bainbridge, Richard Delgado, and Kevin Johnson, and a final rejoinder from me.\nIn Minorities, Shareholder and Otherwise, I demonstrate that corporate law recognizes the relevance of minority status, even while constitutional law more and more insists on minority-blindness. I argue that this is precisely backwards \u2013 that the constitutional domain should require greater judicial vigilance with respect to minority status than the corporate domain. The difficulty of exit from a polity and the inability to negotiate (or at least select among) terms of entry into a polity, not to mention a history of grave injustice, call for special attention to minorities in the constitutional context.\nBy juxtaposing the colorblind aspirations of current constitutional law doctrine with the minority-mindfulness of corporate law, I reveal a fundamental incoherence in the law.\nMinorities, Shareholder and Otherwise identifies this puzzle, and suggests that corporate law has a grip on real world relations that constitutional law increasingly abjures.",
    "title": "Critical Corporate Law, Colorblind Constitutional Law",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Global data flows are the lifeblood of the global economy today and of the technologies of the future. Yet, the regulation of how data is to be handled remains largely the province of national laws. How we resolve the dilemmas of global flows within a nation-state structure will impact the digital economy, free expression, privacy, security, consumer protection, and taxation. Just as we once built an architecture for cross-border flow of goods, we need to build an architecture for cross-border flow of information.",
    "title": "National Data Governance in a Global Economy",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "Ancient physicians engaged in property disputes over the seals they impressed on the containers of their medications, making brand marks the oldest branch of intellectual property. The antiquity of brand marks, however, has not helped their proper understanding by the law. While the conceptual and historical foundations of copyrights and patents continue to be part and parcel of contemporary legal debates, the full history and theorizing on business marks is largely external to trademark doctrine. Furthermore, with only a few and by now outdated exceptions, whatever scholarship exists on these topics has been performed mostly not by legal scholars but by archaeologists, art historians, anthropologists, sociologists, and historians of material culture. Such a striking imbalance suggests that the law is more eager to assume and state what trademarks should be rather than understand how they actually work today. Nor does the law often acknowledge the many different ways in which marks have always been deployed to distinguish both goods and their makers. This is not just a scholarly problem: given the extraordinary importance of brands in the global economy, the growing disjuncture between the way brands function in different contexts and cultures and trademark law\u2019s simplified conceptualization of that function has become a problem with increasingly substantial policy implications.",
    "title": "Brand New World: Distinguishing Oneself in the Global Flow",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "null",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "The New Global Division of Labor",
    "tags": "SSRN",
    "url": "paper.html"
  }, {
    "text": "There is no abstract yet. Move along.",
    "title": "Golan v. Holder",
    "tags": "SSRN",
    "url": "paper.html"
  }]
};
